### ISSUE TITLE
DBView doesn't show my Campaigns

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#4]
Running from my local environment, when I clicked on DBView I cannot find the Campaigns listed on my Home page.  I see the `json` in the DB, but my campaigns are nowhere in the list.  

Why is that?

It seems as if the DBView link is pointing to another DB.  Am I right?

![image](https://user-images.githubusercontent.com/7561473/30525550-6cd1848c-9bbd-11e7-89ab-10150a5057ea.png)

**Comment by paweenwich** [comment]
@daver78  You are correct.  This one relate to the missing conf/davinch.json file that Coa mail to you.  The trouble behind this is we have stage and production.  Code need a way to identify database endpoint to link to.   So, I create a conf/davinch.json  to keep this setting.  However, we put it in our VirtualBox and set ..gitignore to prevent mistakenly pull this file to production.    So, we need to set manually copy this file to each server.  

The find content look like.  

{
    "serverName":"Local",
    "databaseEndPoint":"http://162.243.155.57:5985"
}

One more thing, you need to set proxysetting of /couchdb  to this endpoint also 

ProxyPass /couchdb http://162.243.155.57:5985/
ProxyPassReverse /couchdb http://162.243.155.57:5985/

I am experimenting in removing this ProxyPass thing.  It's on the test stage.  So, please set this for the time being. 

TO CHECK:

1)  check if /couchdb  point to staging database 
type  http://your.devleop.machine/couchdb/a_stage   if show something like 
{"db_name":"a_stage","doc_count":0,"doc_del_count":0,"update_seq":0,"purge_seq":0,"compact_running":false,"disk_size":79,"data_size":0,"instance_start_time":"1505447073524530","disk_format_version":6,"committed_update_seq":0}

then the setting is correct.   The reason is, we put empty database name "a_stage" to stage database only.   If  it return 
{"error":"not_found","reason":"no_db_file"}

this mean, you still are on prod database.

2) check if davinci.json is in place.
just login to davinci and click DBView.  New tab will open with the database "davinci.json" point to, if not found, it will point to prod database.   So, correct setting should bring you to 

http://162.243.155.57:5985/_utils/document.html?dbXXX/campaignlist

**Comment by daver78** [comment]
@paweenwich OK.  Likely that I won't be able to work on this today or tomorrow, but Wed - Friday of this week I will get back into the code and let you know if I have any problems using your suggestion.

Let's leave this open until I do that and verify the solution.

**Comment by daver78** [comment]
@paweenwich I configured as you stated above, and it appears to be working now.  I'll close this issue for now.  Thank you for your help!
