### ISSUE TITLE
How every developer should work with Git and our release strategy

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#7]
@paweenwich Can we open this issue to document our desired workflow for all developers, including me?

I suggest reading this: [https://www.atlassian.com/git/tutorials/comparing-workflows,](https://www.atlassian.com/git/tutorials/comparing-workflows,) and then deciding if any of those workflows sound right for us.
-------
From now I will use this process as advised by @coa0329:

`git branch -a` to see a list of all branches
`git checkout stage` to checkout the stage branch, then make my changes
`git add whatever.html` to add my changes
`git commit -m “”` to commit my changes
`git push` to send my changes to the stage branch in the repo

However, this does not seem to match what everyone else is doing:  It seems like others are creating a branch for the feature/issue they're working on, and pushing that branch to the repo.  

I imagine that they will issue a `pull` request to you, which you'll use to code review and merge their code into `stage`.

Then you'll pull `stage` to the staging environment.

When we're ready, you'll merge `stage` to `master`, and then pull `master` to production.

Is that what you're thinking?

**Comment by paweenwich** [comment]
@daver78 Your imagine is correct.  Except the "pull request" part.    Because, I need to fixed and research a few things myself.  So, I don' have time to manage "pull request".   So, I ask "Fung and Jew" to push their working branch directly to stage also (beside put to their branch as backup code).   

I also use the same work flow as Coa explain to you ( working with stage directly).  I like to experiment if some do branch and put to stage, while others do direct modify.  

We will pull code to staging server at the end of day.  So, Kushal can check w/o the need to setting server.  

When ready, as you said.  we will merge stage to master and pull master to production.

**Comment by daver78** [comment]
@paweenwich Got it!  We will use this for now and see how it goes.

@paagla123 Are you clear on this process?  Any questions?  If not we can close this issue.

**Comment by daver78** [comment]
@paweenwich and @paagla123 I'm closing this.  Seems our process is OK.
